pipeline {
    agent any
    tools {
        maven '3.9.6'
    }
    stages {
        stage('CleanUp') {
            steps {
                deleteDir()
            }
        }
        stage('Build') {
            steps {
                echo 'Faza Build'
            }
        }
        stage('Test') {
            steps {
                echo 'Faza Test'
            }
        }       
        stage('Deliver') {
            steps {
                echo 'Faza Deliver'
            }
        }  
        stage('Finish build') {
            steps {
                echo 'Finish build'
            }
        }                 
    }
}
